# Generated by Django 4.2.1 on 2026-03-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '类型', 'verbose_name_plural': '类型'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': '支出记录', 'verbose_name_plural': '支出记录'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.FloatField(verbose_name='金额'),
        ),
    ]
