# Generated by Django 4.2.1 on 2026-03-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_category_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='account',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='ower',
            new_name='owner',
        ),
    ]
