# Generated by Django 4.2.1 on 2026-03-26 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '收入类型',
                'verbose_name_plural': '收入类型',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='金额')),
                ('date', models.DateField(verbose_name='日期')),
                ('description', models.TextField(default='', verbose_name='收入描述')),
                ('category', models.CharField(max_length=255, verbose_name='分类')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联账户')),
            ],
            options={
                'verbose_name': '收入记录',
                'verbose_name_plural': '收入记录',
            },
        ),
    ]
